//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: protofiles/PacketOpcode.proto
namespace Proto
{
    [global::ProtoBuf.ProtoContract(Name=@"PacketOpcode")]
    public enum PacketOpcode
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Msg_Test", Value=1)]
      Msg_Test = 1
    }
  
}