# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Msg.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='Msg.proto',
  package='Proto',
  syntax='proto2',
  serialized_pb=_b('\n\tMsg.proto\x12\x05Proto\"\x1c\n\rMsg_Test_Data\x12\x0b\n\x03msg\x18\x01 \x02(\t')
)




_MSG_TEST_DATA = _descriptor.Descriptor(
  name='Msg_Test_Data',
  full_name='Proto.Msg_Test_Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='Proto.Msg_Test_Data.msg', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=20,
  serialized_end=48,
)

DESCRIPTOR.message_types_by_name['Msg_Test_Data'] = _MSG_TEST_DATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg_Test_Data = _reflection.GeneratedProtocolMessageType('Msg_Test_Data', (_message.Message,), dict(
  DESCRIPTOR = _MSG_TEST_DATA,
  __module__ = 'Msg_pb2'
  # @@protoc_insertion_point(class_scope:Proto.Msg_Test_Data)
  ))
_sym_db.RegisterMessage(Msg_Test_Data)


# @@protoc_insertion_point(module_scope)
