# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketOpcode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketOpcode.proto',
  package='Proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12PacketOpcode.proto\x12\x05Proto*\x1d\n\x0cPacketOpcode\x12\r\n\x08Msg_Test\x10\xe8\x07')
)

_PACKETOPCODE = _descriptor.EnumDescriptor(
  name='PacketOpcode',
  full_name='Proto.PacketOpcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Msg_Test', index=0, number=1000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=29,
  serialized_end=58,
)
_sym_db.RegisterEnumDescriptor(_PACKETOPCODE)

PacketOpcode = enum_type_wrapper.EnumTypeWrapper(_PACKETOPCODE)
Msg_Test = 1000


DESCRIPTOR.enum_types_by_name['PacketOpcode'] = _PACKETOPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
