# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PacketOpcode.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PacketOpcode.proto',
  package='Proto',
  syntax='proto2',
  serialized_pb=_b('\n\x12PacketOpcode.proto\x12\x05Proto*h\n\x0cPacketOpcode\x12\r\n\x08Msg_Test\x10\x81\x02\x12\x19\n\x14\x43\x32S_JoinOrCreateRoom\x10\xe8\x07\x12\x19\n\x14S2C_JoinOrCreateRoom\x10\xe9\x07\x12\x13\n\x0e\x46rame_Msg_Test\x10\x90N')
)

_PACKETOPCODE = _descriptor.EnumDescriptor(
  name='PacketOpcode',
  full_name='Proto.PacketOpcode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='Msg_Test', index=0, number=257,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='C2S_JoinOrCreateRoom', index=1, number=1000,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='S2C_JoinOrCreateRoom', index=2, number=1001,
      options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='Frame_Msg_Test', index=3, number=10000,
      options=None,
      type=None),
  ],
  containing_type=None,
  options=None,
  serialized_start=29,
  serialized_end=133,
)
_sym_db.RegisterEnumDescriptor(_PACKETOPCODE)

PacketOpcode = enum_type_wrapper.EnumTypeWrapper(_PACKETOPCODE)
Msg_Test = 257
C2S_JoinOrCreateRoom = 1000
S2C_JoinOrCreateRoom = 1001
Frame_Msg_Test = 10000


DESCRIPTOR.enum_types_by_name['PacketOpcode'] = _PACKETOPCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)


# @@protoc_insertion_point(module_scope)
